{
  todo(id: 42) {
    id
    text
    complete
    comments {
      comment
      author {
        name
        profilePicture(size: 50)  {
          uri
          width
          height
        }
      }
    }
  }
}
